"use client";
import { useState } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
// import type { Metadata } from "next"; // Metadata cannot be used in client components

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = { // Metadata needs to be handled differently for client components
//   title: "AttentID | Admin panel",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isSidebarOpen, setIsSidebarOpen] = useState(true);

  const toggleSidebar = () => {
    setIsSidebarOpen(!isSidebarOpen);
  };

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="relative flex h-screen"> {/* Changed to relative for positioning context if needed */}
          <Sidebar isOpen={isSidebarOpen} toggleSidebar={toggleSidebar} />
          <main
            className={`flex-1 overflow-y-auto p-4 transition-all duration-300 ease-in-out ${
              isSidebarOpen ? "ml-64" : "ml-0" // Adjust margin based on sidebar state
            }`}
          >
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
